
import { defineStore } from 'pinia'

export const useShopStore = defineStore("shop", {
  state: () => {
    return {
      sale: [
        {
          id: 'sneakers1',
          img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
          title: "Nike Air Monarch IV",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Nike",
          color: "white",
          category: "sneakers",
        },
        {
          id: 'sneakers2',
          img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
          title: "Nike Air Vapormax Plus",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Nike",
          color: "red",
          category: "sneakers",
        },
        {
          id: 'sneakers3',
          img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
          title: "Nike Waffle One Sneaker",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Nike",
          color: "green",
          category: "sneakers",
        },
        {
          id: 'sneakers4',
          img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
          title: "Nike Running Shoe",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Adidas",
          color: "black",
          category: "sneakers",
        },
        {
          id: 'flats1',
          img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
          title: "Flat Slip On Pumps",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Vans",
          color: "green",
          category: "flats",
        },
        {
          id: 'flats2',
          img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
          title: "Knit Ballet Flat",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "50",
          company: "Adidas",
          color: "black",
          category: "flats",
        },
        {
          id: 'flats3',
          img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
          title: "Loafer Flats",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "50",
          company: "Vans",
          color: "white",
          category: "flats",
        },

        {
          id: 'sneakers5',
          img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
          title: "Nike Zoom Freak",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Nike",
          color: "green",
          category: "sneakers",
        },
        {
          id: 'sneakers6',
          img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
          title: "Nike Men's Sneaker",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Adidas",
          color: "blue",
          category: "sneakers",
        },

        {
          id: 'sneakers7',
          img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
          title: "PUMA BLACK-OCE",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "150",
          company: "Puma",
          color: "green",
          category: "sneakers",
        },
        {
          id: 'sneakers8',
          img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
          title: "Pacer Future Sneaker",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "150",
          company: "Puma",
          color: "red",
          category: "sneakers",
        },
        {
          id: 'sneakers9',
          img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
          title: "Unisex-Adult Super",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "150",
          company: "Puma",
          color: "black",
          category: "sneakers",
        },
        {
          id: 'sneakers10',
          img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
          title: "Roma Basic Sneaker",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "150",
          company: "Puma",
          color: "white",
          category: "sneakers",
        },
        {
          id: 'sneakers11',
          img: "https://m.media-amazon.com/images/I/7128-af7joL.AC_UY575.jpg",
          title: "Pacer Future Doubleknit",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "150",
          company: "Puma",
          color: "black",
          category: "sneakers",
        },
        {
          id: 'sneakers12',
          img: "https://m.media-amazon.com/images/I/81xXDjojYKS.AC_UX575.jpg",
          title: "Fusion Evo Golf Shoe",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "100",
          company: "Puma",
          color: "green",
          category: "sneakers",
        },
        {
          id: 'flat4',
          img: "https://m.media-amazon.com/images/I/719gdz8lsTS.AC_UX575.jpg",
          title: "Rainbow Chex Skate",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "100",
          company: "Vans",
          color: "red",
          category: "flats",
        },
        {
          id: 'sandals1',
          img: "https://m.media-amazon.com/images/I/71gpFHJlnoL.AC_UX575.jpg",
          title: "Low-Top Trainers",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "100",
          company: "Vans",
          color: "white",
          category: "sandals",
        },
        {
          id: 'sandals2',
          img: "https://m.media-amazon.com/images/I/71pf7VFs9CL.AC_UX575.jpg",
          title: "Vans Unisex Low-Top",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "100",
          company: "Vans",
          color: "blue",
          category: "sandals",
        },
        {
          id: 'sandals3',
          img: "https://m.media-amazon.com/images/I/61N4GyWcHPL.AC_UY575.jpg",
          title: "Classic Bandana Sneakers",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "50",
          company: "Nike",
          color: "black",
          category: "sandals",
        },
        {
          id: 'heels1',
          img: "https://m.media-amazon.com/images/I/61bncQ44yML.AC_UX695.jpg",
          title: "Chunky High Heel",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "50",
          company: "Vans",
          color: "black",
          category: "heels",
        },
        {
          id: 'heels2',
          img: "https://m.media-amazon.com/images/I/71czu7WgGuL.AC_UY695.jpg",
          title: "Slip On Stiletto High Heel",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "100",
          company: "puma",
          color: "black",
          category: "heels",
        },
        {
          id: 'heels3',
          img: "https://m.media-amazon.com/images/I/61men05KRxL.AC_UY625.jpg",
          title: "DREAM PAIRS Court Shoes",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "150",
          company: "Nike",
          color: "red",
          category: "heels",
        },
        {
          id: 'sneakers13',
          img: "https://m.media-amazon.com/images/I/519MRhRKGFL.AC_UX575.jpg",
          title: "Nike Air Vapormax Plus",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Nike",
          color: "red",
          category: "sneakers",
        },

        {
          id: 'heels4',
          img: "https://m.media-amazon.com/images/I/51PGWTXgf-L.AC_UY625.jpg",
          title: "Low Mid Block Heels",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "200",
          company: "Nike",
          color: "black",
          category: "heels",
        },
        {
          id: 'heels5',
          img: "https://m.media-amazon.com/images/I/616sA5XUKtL.AC_UY675.jpg",
          title: "Chunky High Heel",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "50",
          company: "Adidas",
          color: "black",
          category: "heels",
        },
        {
          id: 'heels6',
          img: "https://m.media-amazon.com/images/I/71h5+MbEK7L.AC_UY625.jpg",
          title: "Amore Fashion Stilettos",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "150",
          company: "Adidas",
          color: "white",
          category: "heels",
        },
        {
          id: 'heels7',
          img: "https://m.media-amazon.com/images/I/61uw5RDxKQL.AC_UY625.jpg",
          title: "Bridal Sandals Glitter",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "50",
          company: "Adidas",
          color: "black",
          category: "heels",
        },
        {
          id: 'flat5',
          img: "https://m.media-amazon.com/images/I/71yhoZP0l6L.AC_UY695.jpg",
          title: "Wedding Prom Bridal",
          reviews: "(123 reviews)",
          prevPrice: "$140,00",
          newPrice: "50",
          company: "Adidas",
          color: "black",
          category: "flats",
        },

      ],
      cart: [],
    };
  },

  getters: {
    cartQuantity() {
      return this.cart.reduce((prev, curr) => {
        return prev + curr.quantity;
      }, 0);
    },
    cartSubTotal() {
      return this.cart.reduce((prev, curr) => {
        return prev + curr.newPrice * curr.quantity
      }, 0)
    },
  },

  actions: {
    addToCart(item) {
      const existingId = this.cart.findIndex((cartItem) => cartItem.id === item.id);

      if (existingId !== -1) {
        this.cart[existingId].quantity += 1;
      } 
      else {
        this.cart.push({
          ...item,
          quantity: 1,
        });
      }
    },
    removeItem(removedItem) {
      this.cart = this.cart.filter((item) => item.id !== removedItem.id);
    },
  },


});
